name: nuconta_marketplace
description: A Flutter app where users spend their NuConta balance on awesome products.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^0.1.3

  #https://pub.dev/packages/get_it
  get_it: ^4.0.2

  #https://pub.dev/packages/dio
  dio: ^3.0.9

  #https://pub.dev/packages/graphql
  graphql: 3.0.1-beta.3

  #https://pub.dev/packages/email_validator
  email_validator: ^1.0.4

  #https://pub.dev/packages/intl
  intl: ^0.16.1
  
  #https://pub.dev/packages/mobx
  mobx: ^1.2.1

  #https://pub.dev/packages/flutter_mobx
  flutter_mobx: ^1.1.0

  #https://pub.dev/packages/provider
  provider: ^4.1.3

  #https://pub.dev/packages/shared_preferences
  shared_preferences: ^0.5.7+3

  #https://pub.dev/packages/lottie
  lottie: ^0.4.0+1

  #https://pub.dev/packages/device_info
  device_info: ^0.4.2+4

  #https://pub.dev/packages/package_info
  package_info: ^0.4.1

  #https://pub.dev/packages/dartz
  dartz: ^0.9.1

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  
  #https://pub.dev/packages/build_runner  
  build_runner:

  #https://pub.dev/packages/mobx_codegen
  mobx_codegen:
    
  #https://pub.dev/packages/effective_dart
  effective_dart: ^1.2.3

  #https://pub.dev/packages/mockito
  mockito: ^4.1.1


flutter:

  uses-material-design: true
  assets:
    - lib/assets/
  
  fonts:
    - family: Gotham
      fonts:
        - asset: fonts/GothamSSm-Black.ttf
          weight: 900
        - asset: fonts/GothamSSm-Bold.ttf
          weight: 700
        - asset: fonts/GothamSSm-Book.ttf
          weight: 400
        - asset: fonts/GothamSSm-Light.ttf
          weight: 300
        - asset: fonts/GothamSSm-Medium.ttf
          weight: 500